### ISSUE TITLE
Crash when clicking on ChromatiCraft Chromic Lexicon in library

### ISSUE THREAD

**Issue by Haggle1996** [joshiejack/Enchiridion#57]
Steps to reproduce:

Open Enchiridion 2. Click 'Library' in top right. Click on 'Chromic Lexicon' icon at top. Crash to desktop with NullPointerException.

https://gist.github.com/Haggle1996/86586d8444595a9c598e

**Comment by TBK0000** [comment]
Have you tried a newer version of ChromatiCraft? - https://sites.google.com/site/reikasminecraft/latest-downloads

**Comment by Haggle1996** [comment]
Same crash occurs with the latest version of Enchiridion and ChromatiCraft (v7f), minimal modset.

**Comment by shadoxxhd** [comment]
i think this occurs because the chromatic lexicon contains info fragments (internal inventory), when it checks for those it returns a null pointer (there's probably not even an itemstack associated to the book GUI from enchiridion). difficult to fix as without fragments the lexicon is pretty much worthless, and tracking fragment progress could be difficult (at least in a general way - and i guess you dont want to do a lot of coding for supporting one single mod). i see 2 solutions:

-in the enchiridion menu, you have access to a world based (saved in level.dat) inventory which stores all the books, so you can update (add new fragments) things like the chromatic lexicon while just having to add other books (the book would be passed as the "use"d item stack)

-creating a temporary item stack of the book when you open it
+: less storage requirement, less chance for updates to break things
-: either you add a full or an empty lexicon, there is no option inbetween

**Comment by ReikaKalseki** [comment]
I can add an API hook for you to get fragments by name on a book or player, but I get the feeling that will not be enough.


Also, I know nothing of Enchiridon, not even what it does.

**Comment by shadoxxhd** [comment]
maybe, as a workaround, temporarily switching a cached version of the lexicon with the currently active hotbar item?

**Comment by ReikaKalseki** [comment]
That does not work either.

**Comment by shadoxxhd** [comment]
how would that be different from opening the book normally?

**Comment by ReikaKalseki** [comment]
Because any cached version is A) likely in accessible, B) may not exist and C) likely to be out of sync.

**Comment by shadoxxhd** [comment]
it might work if it would copy the lexicon the player gets at the start of the game, store it into a hidden 1 slot enderchest-like (playerbound) inventory and switch it with the active item every time you try to access it via enchiridion, though it would require the mod to be existent on the server to work in MP. another option would be to simply cache the UI (maybe as an interactive book?) and show it directly without accessing the standard methods, though it would be quite difficult to model the interactive part dynamically (i.e. without doing it manually for every update/new book).

**Comment by ReikaKalseki** [comment]
That is a massive rewrite that I doubt will even work, let alone solve this issue.
